name: Beautech
description: Hair Salon, Massage Salon, Spas and much more


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.2
  provider: ^4.3.3
  shared_preferences: ^0.5.12+4
  cloud_functions: ^0.6.0+1
  firebase_messaging: ^7.0.3
  cloud_firestore: ^0.14.4
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.0
  flutter_form_builder: ^4.2.0
  scoped_model: ^1.1.0
  smart_select: ^4.3.2
  permission_handler: ^5.0.1+1
  file_picker: ^2.1.6
  firebase_storage: ^5.2.0  
  faker: ^1.3.0
  flappy_search_bar: ^1.7.2
  adaptive_breakpoints: ^0.0.4
  flutter_tabler_icons: 1.0.2
  firebase_analytics: ^5.0.2
  flutter_svg: ^0.19.3
  get_it: ^5.0.0
  intl: ^0.16.1
  google_sign_in: ^4.5.9
  uni_links: ^0.4.0
  image_picker: ^0.6.3+1
  image_cropper: ^1.2.0
  url_launcher: ^5.7.10
  sign_in_with_apple: ^2.5.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter


dependency_overrides:
  intl: ^0.17.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/female-hair-cut-with-scissors.svg


